[tool.bumpversion]
current_version = "1.5.0"

parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        -                             # dash separator for pre-release section
        (?P<pre_l>[a-zA-Z-]+)?       # pre-release label (optional)
        (?P<pre_n>[0-9]+)?           # pre-release version number (optional)
    )?                               
"""

[tool.bumpversion.parts.major]
independent = true

[tool.bumpversion.parts.minor]
independent = true

[tool.bumpversion.parts.patch]
independent = true

[tool.bumpversion.parts.pre_l]
values = ["dev", "rc", ""]
optional_value = ""

[tool.bumpversion.parts.pre_n]
independent = true
first_value = "0"

serialize = [
    "{major}.{minor}.{patch}",
    "{major}.{minor}.{patch}-{pre_l}{pre_n}"
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "src/deepforest/_version.py"
