repos:
- repo: local
  hooks:
    - id: update-citations
      name: Update citation count
      entry: bash -c 'python fetch_google_scholar.py && git add citation_count.json'
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-json
      files: citation_count.json

- repo: https://github.com/google/yapf
  rev: v0.40.1
  hooks:
    - id: yapf
      language: python
      additional_dependencies: [toml]
      args: ['-i', '--style', '.style.yapf']
      files: |
        (?x)^(
          src/deepforest.*\.py|
          fetch_google_scholar\.py
        )$

- repo: local
  hooks:
    - id: docformatter
      name: docformatter
      entry: docformatter
      language: system
      types: [python]
      args: ['--in-place']
      files: |
        (?x)^(
          src/deepforest.*\.py
        )$
