name: Conda package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: "CI setup"

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.11", "3.10" ]
        os: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenCV dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libegl1-mesa
          sudo apt-get install -y python3-opencv

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: DeepForest
          environment-file: environment.yml
          create-args: "python=${{ matrix.python-version }}"
          cache-environment: true
          cache-downloads: true

      - name: Run pytest
        run: micromamba run -n DeepForest pytest -v

      - name: Check style
        run: micromamba run -n DeepForest yapf -d --recursive deepforest/ --style=.style.yapf
          
      - name: Check notebook build
        run: micromamba run -n DeepForest pytest --nbmake docs/*.ipynb

      - name: Test Docs
        run: |
          cd docs && micromamba run -n DeepForest make clean && make html SPHINXOPTS="-W"
